version: '2'
services:
  fe:
    image: quiz_fe:latest
    ports:
      - "80:80"
  be:
    image: quiz_be:latest
    environment:
      - API_PORT=30303
    ports:
      - "30303:30303"
    expose:
      - "30303"
